<?php

namespace AppBundle\Repository;

/**
 * CheckSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
