# To get started with security, check out the documentation:
# See [guide](http://symfony.com/doc/current/book/security.html)
# See [guide](http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate)

security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
            # memory:
            #     users:
            #         ryan:
            #             password: $2a$12$LCY0MefVIEc3TYPHV9SNnuzOfyr2p/AXIGoQJEDs4am4JwhNz/jli
            #             roles: 'ROLE_USER'
            #         admin:
            #             password: $2a$12$cyTWeE9kpq1PjqKFiWUZFuCRPwVyAZwm4XzMZ1qPUFl7/flCM3V0G
            #             roles: 'ROLE_ADMIN'
        ioboxes_persisted_entity:
            entity:
                class:              AppBundle:User
                property:           username
                # name of a non-default entity manager
                manager_name:       ~
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
#            form_login:
#                # submit the login form here
#                check_path: /login_check
#
#                # the user is redirected here when they need to log in
#                login_path: /login
#
#                # if true, forward the user to the login form instead of redirecting
#                #use_forward: false
#
#                # login success redirecting options (read further below)
#                #always_use_default_target_path: false
#                #default_target_path:            /
#                #target_path_parameter:          _target_path
#                #use_referer:                    false
#
#                # login failure redirecting options (read further below)
#                #failure_path:    /foo
#                #failure_forward: false
#                #failure_path_parameter: _failure_path
#                #failure_handler: some.service.id
#                #success_handler: some.service.id
#
#                # field names for the username and password fields
#                #username_parameter: _username
#                #password_parameter: _password
#
#                # csrf token options
#                #csrf_parameter: _csrf_token
#                #intention:      authenticate
#                #csrf_provider:  my.csrf_provider.id
#
#                # by default, the login form *must* be a POST, not a GET
#                #post_only:      true
#                #remember_me:    false
#
#                # by default, a session must exist before submitting an authentication request
#                # if false, then Request::hasPreviousSession is not called during authentication
#                # new in Symfony 2.3
#                #require_previous_session: true

            #logout:
            #    path:   /logout
            #    target: /
            #    invalidate_session: false
            #    delete_cookies:
            #        a: { path: null, domain: null }
            #        b: { path: null, domain: null }
            #    handlers: [some.service.id, another.service.id]
            #    success_handler: some.service.id

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        # anonymous access
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        # require ROLE_USER for /*
        - { path: ^/, roles: ROLE_USER }

    encoders:
        #Symfony\Component\Security\Core\User\User:
        #    algorithm: bcrypt
        #    cost: 12
        # AppBundle\Entity\User:
        #     algorithm: bcrypt
        #     cost: 12
        AppBundle\Entity\User: plaintext
